name: pusht_lowdim_obsact

# obs_dim: 20 # 9*2 keypoints + 2 state
obs_dim: 18 # 9*2 keypoints
action_dim: 2
keypoint_dim: 2

env_runner:
  _target_: diffusion_policy.env_runner.pusht_keypoints_runner.PushTKeypointsRunner
  keypoint_visible_rate: ${keypoint_visible_rate}
  n_train: 1
  n_train_vis: 1
  train_start_seed: 0
  n_test: 1
  n_test_vis: 1
  legacy_test: True
  test_start_seed: 100000
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  n_latency_steps: ${n_latency_steps}
  fps: 10
  agent_keypoints: False
  past_action: ${past_action_visible}
  n_envs: null

dataset:
  _target_: diffusion_policy.dataset.pusht_dataset_obsact.PushTLowdimObsactDataset
  # zarr_path: data/pusht/pusht_cchi_v7_replay.zarr
  zarr_path: data/pusht_demo_left_v2.zarr
  horizon: ${horizon}
  pad_before: 0
  pad_after: 0
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
